code-collabo/node-mongo-cli

- .github/workflows/node.js.yml
* Sets github action for develop branch
Ping @code-collabo/node-mongo-cli @jiobiagba @chasscepts @torsami77 @IsraelObiagba @joshuacharley @Akaypee @Akpjunior94 @Kizito25 @Ifycode
> Set github action for develop branch

- README.md
* Updates readme as mentioned in #19 
Check the following:
ping @code-collabo/node-mongo-cli
> 19 - Update readme

- README.md
* Fixes issue code-collabo/node-mongo-cli#38
**Details:**
* Add detailed info to **contributing to node-mongo-cli** section of readme to help first time contributors understand how to contribute.
> 38 - update contributing to node-mongo-cli section of readme

- README.md
* Fixes issue code-collabo/node-mongo-cli#44
* Fixes eligibility info & additionally adds all repos to related repos list.
> 44 - Update README.md

- README.md
* Fixes issue code-collabo/node-mongo-cli#34
* Adds GitHub readme stats
> 34 - Add readme stats

- src/cli.js
**This pull request makes the following changes**:
* Fixes issue code-collabo/node-mongo-cli#43
**Details**:
* Adds prompt for options template
**Testing checklist**:
> 43 - Add prompt for options.template

- src/cli.js
- src/main.js
* Fixes issue code-collabo/node-mongo-cli#54
Configures --git ( -g) and --skip-git (-x) flags.
> 54 - Configure git  and skip git flags

- .github/ISSUE_TEMPLATE/report-a-bug.md
* Fixes issue #2 (template aspect)
* Adds "Report a bug" template 
> Create bug template

- src/cli.js
* Fixes issue code-collabo/node-mongo-cli#55
**Details:**
* Add details soon...
> 55 - Fix folder content overwrite

- bin/customize-preinstall
- package.json
* Fixes issue code-collabo/node-mongo-cli#73 
**Details:**
* Fix for dependency install issues
> 73 - Temporary fix for install bug/issue

- LICENSE
* Updates LICENSE file with note on @dkundel's project
> Update LICENSE with note on @dkundel's tutorial/project

- .gitignore
- package-lock.json
- package.json
- src/main.js
- templates/esm/package.json
* Fixes issue code-collabo/node-mongo-cli#96  
**Commits that take care of this issue**
* Use spawn: https://github.com/code-collabo/node-mongo-cli/pull/97/commits/2aca6ba8b755a4e77e4e1ae7f0eb63f64d2eb27d
* Fix error: https://github.com/code-collabo/node-mongo-cli/pull/97/commits/10a0aef85947e766295616e4ae40737e19ea1930
> Make npm install progress show up in terminal

- src/cli.js
- src/help.js
- src/prompts/template.js
* Fixes issue code-collabo/node-mongo-cli#101  
**Details:**
* Fix error when flag is not among those configured in args
* Extra: Fix help info message and console message for skipPrompts
> Fix error when flag is not among those configured in args

- .github/workflows/node.js.yml
- LICENSE
* Tests that code works in node version 16x
> Test workflow for node v16

- README.md
- doc/README.md
> Add cli gif and npm badges

- src/main.js
* Fixes issue code-collabo/node-mongo-cli#issueNumberHere 
**Details:**
- Adds fix for windows OS error when installing cli
> Fix install issues for windows OS

- doc/boilerplate-templates.md
- doc/contribution-guide/development-mode.md
* Minor fixes for boilerplate template doc
> Minor fixes for boilerplate template doc and development

- README.md
- doc/README.md
Add link to doc in readme, add link to npm or repo in doc
> Add link to doc in readme, add link to npm or repo in doc

- README.md
- doc/README.md
Reverts code-collabo/node-mongo-cli#127
> Revert "Add link to doc in readme, add link to npm or repo in doc"

- README.md
- doc/README.md
Reverts code-collabo/node-mongo-cli#130
> Revert "Revert "Add link to doc in readme, add link to npm or repo in doc""

- README.md
- doc/README.md
> Add Operating Systems supported to doc

- templates/cjs/src/app.js
* Fixes issue code-collabo/node-mongo-cli#134
**Details:**
* Setup for '...'
* Adds '...' etc.
> variable name changed

- README.md
- doc/README.md
- doc/boilerplate-templates.md
* Clean up and clarify confusing parts of the documentation.
> Clean up and clarify confusing parts of the documentation

- README.md
- doc/README.md
* Update npm badge and operating systems - readme and doc
> Update npm badge and operating systems - readme

- package-lock.json
- package.json
- templates/cjs/README.md
- templates/esm/README.md
* Updates package version number to 1.0.2 in preparation for publish to npm.
> Update cli package version - 1.0.2

- src/prompts/foldername.js
* Fixes issue code-collabo/node-mongo-cli#153
> renamed defaultFolderName from node-mongo-kit to nm-kit

- .all-contributorsrc
- README.md
* Rearrange contributors in rc & readme files
> Rearrange contributors in rc & readme files

- README.md
- doc/README.md
> Changed Titles in Read me & doc

- README.md
* Fixes issue: #178 
**Details:**
* Create a link to typescript repository.
> docs: update readme to include typescript repo

- src/main.js
> cli: create .env files for templates

- templates/cjs/README.md
* Fixes issue code-collabo/node-mongo-cli#167
> Fix cjs template readme

- templates/esm/README.md
* Fixes issue code-collabo/node-mongo-cli#168
> Fix esm template readme

- doc/boilerplate-templates.md
* Fixes issue code-collabo/node-mongo-cli#185
> Add introductory paragraph for templates

- src/main.js
* Fixes issue #142 
* code-collabo/node-mongo#2
**Checklist:**
> fix: CLI @code-collabo/node-mongo-cli doesn't work on linux #142

- .github/ISSUE_TEMPLATE/api-user-error-report.md
* Fix https://github.com/code-collabo/node-mongo/issues/31
> Fix: Create an "API user error report" issue template for users that encounter errors that prevent them from using the API boilerplate template.

- .github/ISSUE_TEMPLATE/api-user-error-report.md
- .github/ISSUE_TEMPLATE/cli-user-error-report.md
- src/main.js
* Fixes code-collabo/put-repo-name-where-the-issue-is-located-here#putTheIssueNumberHere 
> Cleanup 1 - PRs in prep for version v2.0.0 release

- package-lock.json
- package.json
* Fixes code-collabo/node-mongo#24
> FIX: Upgrade all the dependencies in node-mongo-cli repo's package.json to latest in preparation for releasing v.2.0.0 of the CLI
