src/cli.js
**This pull request makes the following changes**:
* Fixes issue code-collabo/node-mongo-cli#36
**Details**:
* Adds prompt for options.folderName
**Testing checklist**:
=> 36 - Add prompt for options.folderName

bin/customize-preinstall, package-lock.json, package.json, src/customize/customize.js
**This pull request makes the following changes**:
* Fixes issue code-collabo/node-mongo-cli#49
**Details**:
* Customize cli on preinstall
**Testing checklist**:
=> 49 - Customize cli on preinstall

src/cli.js
* Fixes issue code-collabo/node-mongo-cli#57
Configures --yes flag and -y alias.
=> 57 - configure --yes flag

src/cli.js, src/main.js
* Fixes issue code-collabo/node-mongo-cli#53
Configures --install (-i) and --skip-install (-s)
=> 53 - configure install and skip Install flags

src/main.js
This pull request is part of fixes made to code-collabo/node-mongo-cli#57 which was omitted in pull request #62
=> 57 - import execa to fix undefined error

.github/ISSUE_TEMPLATE/create-a-task.md
* Fixes issue #2 (template aspect)
* Adds "Create a task" template 
=> Create task creation template

src/cli.js
* Fixes issue code-collabo/node-mongo-cli#71 
**Details:**
* Detect, change and increment `defaultFolderName` if already in use
=> Detect, change & increment defaultFolderName if already in use

src/cli.js
* Fixes issue code-collabo/node-mongo-cli#76 
**Details:**
* Adds fix wrong prompt when folderName arg is not present.
* Related to issue #71 
=> 76 - Fix wrong prompt when folderName arg is not present

src/cli.js
* Fixes issue code-collabo/node-mongo-cli#77 
**Details:**
* Stops empty folder prompt from downloading template into src folder, by pushing empty string `''` into `rootDirContent` array.
* Adds console message `Folder name cannot be empty` for empty string.
=> 77 - Fix empty folder prompt bug

.editorconfig
Made **quote_type** rule applicable to both .js and .ts files
=> Changed Made quote_type rule

src/cli.js, src/main.js, src/prompts/folder.js, src/prompts/template.js
* Fixes issue code-collabo/node-mongo-cli#72
**Details:**
* Moves code for (folder, template and skip) prompts in to separate functions and files in preparation for code refactoring and documentation.
* Renames the functions.
* Removes console.log messages that are either confusing or performing the work of the `--help` flag.
* Also fixes issues with skipPrompt i.e `--yes` flag.
=> Separate folder and template Prompt functions and move to another file

src/cli.js, src/main.js, src/prompts/folder.js, src/prompts/template.js
* Fixes issue code-collabo/node-mongo-cli#87 
**Details:**
* Fixes folder increment i.e. prevents prompt when folder name matches default folder name.
=> Fix default folder name increment

src/cli.js, src/help.js
* Fixes issue code-collabo/node-mongo-cli#85 
**Details:**
* Configures `--help` flag and alias `-h` to return commands, examples and flags for running the project.
=> Configure help flag to work

README.md
* Fixes readme grammar, typo, updates links and any other relevant thing needed for production/publishing. 
=> Final readme fix in preparation for publishing

README.md, package.json, templates/cjs/LICENCE, templates/cjs/package.json, templates/esm/LICENCE, templates/esm/package.json
* Adds all settings needed for release on npm.
=> v1.0.0 release npm publish settings

README.md, doc/README.md
* Fixes #172 
**Details:**
* Adds : "Replace `<folder_name>` with your preferred folder name. Replace `<template>` with any of these: esm, cjs or ts (note: the ts template is not available yet)." to prompts section
=> update prompts section

src/main.js
* Fix https://github.com/code-collabo/node-mongo/issues/33
=> Fix: Generate/create ISC license files for the template that the CLI generates for users

src/main.js
* Fixes https://github.com/code-collabo/node-mongo/issues/34
=> Fix: The .env/.env.example files generated by the CLI still use old content

src/prompts/template.js, templates/ts/dummy_file.txt, templates/ts/package.json
* Fixes code-collabo/node-mongo#29
=> FIX: Make CLI generate ts template too

src/cli.js
* Fix https://github.com/code-collabo/node-mongo/issues/32
=> Fix: Help CLI user know where to report errors and that manual download options for API templates exist if they encounter error while using the CLI
